site_name: AtPack Parser
site_description: A Python library and CLI tool for parsing AtPack files
site_author: Sébastien Celles
site_url: https://s-celles.github.io/atpack-python-parser/

repo_name: s-celles/atpack-python-parser
repo_url: https://github.com/s-celles/atpack-python-parser

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

edit_uri: edit/main/docs/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Installation: installation.md
  - CLI Usage: cli-usage.md
  - TUI Usage: tui-usage.md
  - Interactive Mode: interactive-mode.md
  - Python API: api-usage.md
  - Examples: examples.md
  - API Reference: api-reference.md
  - Development: development.md
  - Legal Information: legal.md
